rvm:
  - 2.1.8
  - 2.2.4
  - 2.3.0
  - ruby-head
install: bundle install
before_install: gem install bundler -v 1.11.2
script: bundle exec rake spec
gemfile:
  - gemfiles/4.0.gemfile
  - gemfiles/4.1.gemfile
  - gemfiles/4.2.gemfile
  - gemfiles/5.0.gemfile
matrix:
  allow_failures:
    - gemfile: gemfiles/5.0.gemfile
    - rvm: ruby-head
  fast_finish: true
